name: deploy

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'
  workflow_run:
    workflows:
      - test
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}
      - name: cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: show git status
        run: git status
      - name: package
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: list packaged files
        uses: actions-rs/cargo@v1
        with:
          command: package
          args: --list
      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{secrets.crate_token}}
