name: deploy

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
      - name: Show git status
        run: git status
      - name: Package
        run: cargo package
      - name: List packaged files
        run: cargo package --list
      - name: Publish
        run: cargo publish --token ${{secrets.crate_token}}
