name: test

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v1

      - name: Setup | Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}

      - name: Setup | Cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}

      - name: Setup | Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Test | Clippy
        run: cargo clippy

      - name: Test | Unit test for ncmdump
        run: cargo test --release --all-features --package ncmdump

      - name: Test | Unit test for ncmdump-bin
        run: cargo test --release --all-features --package ncmdump-bin
