name: test

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --release --all-features
