name: test

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}
      - name: cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
